#!/usr/bin/env python3
"""
embed_token.py - release-time helper that embeds the telemetry PAT into the wheel.

Reads `.env.release` (gitignored), pulls WORLD_MODEL_TELEMETRY_TOKEN, and
writes `world_model_server/_embedded_token.py` (also gitignored). The
generated file is force-included by pyproject.toml so it ships inside the
wheel but never enters git.

Workflow:
    echo 'WORLD_MODEL_TELEMETRY_TOKEN=ghp_yourreleasePAT' > .env.release
    python3 scripts/embed_token.py            # writes _embedded_token.py
    python3 -m build --sdist --wheel          # bundles the token

If `.env.release` is missing or the token is empty, the script writes an
_embedded_token.py with EMBEDDED_TOKEN = "". The wheel still installs;
telemetry just silently no-ops (because telemetry.py treats an empty
token as "no token configured"). That's deliberate: it means contributors
can build wheels locally without a PAT and ship test artifacts that
contain no credentials.

Exit codes:
    0 - wrote _embedded_token.py (with or without a real token)
    1 - validation failure (malformed token, IO error)
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_RELEASE = REPO_ROOT / ".env.release"
OUT_PATH = REPO_ROOT / "world_model_server" / "_embedded_token.py"

# A committed stub at OUT_PATH always exists (EMBEDDED_TOKEN = ""). This
# script overwrites it during a release build, then the user MUST run
# `git update-index --assume-unchanged world_model_server/_embedded_token.py`
# (or just be careful not to commit it). The repo has a test --
# tests/test_v073_features.py::test_embedded_token_stub_is_empty -- that
# catches accidental commits of a populated file.

# GitHub PAT formats we accept. Fine-grained PATs start with `github_pat_`
# (87 chars typical); classic PATs start with `ghp_` (40 chars typical).
# We accept either; the user picks whichever scope model they prefer.
_VALID_PREFIXES = ("github_pat_", "ghp_")


def _read_env_release() -> str:
    """Parse .env.release. Returns the token string, or '' if file missing
    or token unset."""
    if not ENV_RELEASE.exists():
        return ""
    for raw in ENV_RELEASE.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        if key.strip() != "WORLD_MODEL_TELEMETRY_TOKEN":
            continue
        # Strip surrounding quotes if present
        v = value.strip()
        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            v = v[1:-1]
        return v
    return ""


def _validate(token: str) -> None:
    """Raise SystemExit on malformed tokens. Empty is allowed (no-op build)."""
    if not token:
        return
    if not any(token.startswith(p) for p in _VALID_PREFIXES):
        sys.stderr.write(
            "embed_token: token does not match expected prefix.\n"
            f"  expected one of: {_VALID_PREFIXES}\n"
            f"  got: {token[:12]}...\n"
            "If this is a custom test token, edit _VALID_PREFIXES at your own risk.\n"
        )
        sys.exit(1)
    if len(token) < 30:
        sys.stderr.write(
            f"embed_token: token looks too short ({len(token)} chars). Aborting.\n"
        )
        sys.exit(1)


def _write(token: str) -> None:
    """Emit _embedded_token.py. The file is overwritten on every run."""
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    contents = (
        '"""\n'
        "Generated by scripts/embed_token.py. Do not edit by hand.\n"
        "This file is gitignored and is only present in built wheels.\n"
        '"""\n'
        "\n"
        f"EMBEDDED_TOKEN = {token!r}\n"
    )
    OUT_PATH.write_text(contents)


def main() -> None:
    # Allow override from env var so CI can supply the token without an
    # on-disk .env.release. Useful for GitHub Actions secrets later.
    token = os.environ.get("WORLD_MODEL_TELEMETRY_TOKEN", "") or _read_env_release()
    _validate(token)
    _write(token)
    if token:
        sys.stdout.write(
            f"embed_token: wrote {OUT_PATH.relative_to(REPO_ROOT)} "
            f"with a {len(token)}-char token.\n"
        )
    else:
        sys.stdout.write(
            f"embed_token: wrote {OUT_PATH.relative_to(REPO_ROOT)} "
            "with EMBEDDED_TOKEN=''. Telemetry will silently no-op in this build.\n"
        )


if __name__ == "__main__":
    main()
